apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: prtdomingopipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prtdomingopipelinesjavascriptdocker 
    spec:
      containers:
        - name: prtdomingopipelinesjavascriptdocker 
          image: acrdemoph.azurecr.io/prtdomingopipelinesjavascriptdocker
          ports:
          - containerPort: 8080